const translations = {
  en: {
    no_device: "Select a TP-Link Easy Smart device in the card editor.",
    no_entities: "No entities were found for this device.",
    online: "Online",
    offline: "Unavailable",
    ports: "ports active",
    port: "Port",
    link_down: "Link down",
    traffic: "Estimated traffic",
    download: "RX",
    upload: "TX",
    total: "Total",
    enabled: "Enabled",
    flow_control: "Flow control",
    speed_duplex: "Speed and duplex",
    qos_priority: "QoS priority",
    poe: "PoE",
    cable_test: "Run cable test",
    cable: "Cable",
    cable_length: "Length",
    packets: "Packet counters",
    good: "good",
    bad: "bad",
    controls: "Switch controls",
    leds: "LEDs",
    igmp_snooping: "IGMP snooping",
    igmp_report_suppression: "IGMP report suppression",
    loop_prevention: "Loop prevention",
    qos_mode: "QoS mode",
    configuration: "VLAN and LAG",
    reboot: "Reboot",
    web_ui: "Web interface",
    confirm_reboot: "Reboot the switch now? Network access may be interrupted.",
    confirm_disable:
      "Disable this port? Connected devices will lose network access.",
    confirm_cable:
      "Run a cable test? This can briefly interrupt the port link.",
    choose_device: "Device",
    title: "Title (optional)",
    view: "Layout",
    compact: "Compact",
    front_panel: "Front panel",
    detailed: "Detailed",
    options: "Visible sections",
    show_traffic: "Traffic",
    show_controls: "Controls",
    show_configuration: "VLAN and LAG",
    confirm_actions: "Confirm disruptive actions",
  },
  fr: {
    no_device: "Sélectionnez un appareil TP-Link Easy Smart dans l’éditeur.",
    no_entities: "Aucune entité n’a été trouvée pour cet appareil.",
    online: "En ligne",
    offline: "Indisponible",
    ports: "ports actifs",
    port: "Port",
    link_down: "Lien inactif",
    traffic: "Trafic estimé",
    download: "RX",
    upload: "TX",
    total: "Total",
    enabled: "Activé",
    flow_control: "Contrôle de flux",
    speed_duplex: "Vitesse et duplex",
    qos_priority: "Priorité QoS",
    poe: "PoE",
    cable_test: "Tester le câble",
    cable: "Câble",
    cable_length: "Longueur",
    packets: "Compteurs de paquets",
    good: "valides",
    bad: "erronés",
    controls: "Contrôles du switch",
    leds: "LED",
    igmp_snooping: "IGMP snooping",
    igmp_report_suppression: "Suppression des rapports IGMP",
    loop_prevention: "Prévention des boucles",
    qos_mode: "Mode QoS",
    configuration: "VLAN et LAG",
    reboot: "Redémarrer",
    web_ui: "Interface web",
    confirm_reboot:
      "Redémarrer le switch maintenant ? Le réseau sera momentanément interrompu.",
    confirm_disable:
      "Désactiver ce port ? Les appareils connectés perdront leur accès réseau.",
    confirm_cable:
      "Lancer le test du câble ? La liaison peut être brièvement interrompue.",
    choose_device: "Appareil",
    title: "Titre (facultatif)",
    view: "Disposition",
    compact: "Compacte",
    front_panel: "Façade",
    detailed: "Détaillée",
    options: "Sections visibles",
    show_traffic: "Trafic",
    show_controls: "Contrôles",
    show_configuration: "VLAN et LAG",
    confirm_actions: "Confirmer les actions perturbatrices",
  },
};

export function localize(language, key) {
  const locale = String(language || "en").split("-")[0];
  return translations[locale]?.[key] || translations.en[key] || key;
}
